name: Publish Pull Request Summary

description: Publish a summary of a pull request to the workflow run summary.

inputs:
  url:
    description: The URL of the pull request to summarize.
    required: true
  heading:
    description: The heading for the summary section.
    required: false
    default: Pull Request Created

runs:
  using: composite
  steps:
    - name: Publish Pull Request Summary
      run: ${{ github.action_path }}/src/publish_pull_request_summary.sh
      shell: sh
      env:
        PULL_REQUEST_URL: ${{ inputs.url }}
        HEADING: ${{ inputs.heading }}
